### ISSUE TITLE
Glider DAC Map, Summary Statistics and glider day counter not loading

### ISSUE THREAD

**Issue by BeckyBaltes** [ioos/ioosngdac#130] opened 2017-08-18 20:16 UTC
@benjwadams @Bobfrat  Please move this issue if needed. The glider map banner at the top of the legend used to display glider days this year, but it's not loading.  Also the summary statistics says, "no information available." Please see what's going on.

**Comment by Bobfrat** [comment] 2017-08-21 15:04
Getting an error while parsing the [status page](https://data.ioos.us/gliders/status/static/json/status.json)

For Nemesis-20170512T0000 it's failing while trying to get the glider start date (ts0). I'll add some error checking.

```
"title": "Nemesis-20170512T0000",
"ts0": "",
"ts1": "2017-08-02T19:16:37Z",
```

**Comment by benjwadams** [comment] 2017-08-21 17:12
Related: https://github.com/ioos/ioosngdac/issues/126
I believe I recall @kerfoot saying on the call that only one of the Nemesis datasets had this issue.  Notice that https://data.ioos.us/gliders/erddap/info/Nemesis-20170412T0000/index.html has `time_coverage_start` whereas https://data.ioos.us/gliders/erddap/info/Nemesis-20170512T0000/index.html does not.

**Comment by Bobfrat** [comment] 2017-08-21 19:34
@BeckyBaltes this should be resolved now but the numbers are inaccurate because it's ignoring the Nemesis dataset that doesn't have a start time.

**Comment by kwilcox** [comment] 2017-12-21 17:34
@BeckyBaltes @Bobfrat @benjwadams I came across this issues while searching for issues regarding`Nemesis-20170512T0000`. This dataset does indeed have errors. There is a `time` value of `-2.41265573455303e+105`. This is most likely the root cause of why `time_coverage_start` isn't populated... that number can't be converted to a valid `datetime` using standard algorithms.

Will this dataset be fixed on the DAC side or should other uses of the DAC develop work arounds themselves to ignore problem datasets?

**Comment by Bobfrat** [comment] 2017-12-21 19:53
@kwilcox 
Good question, we currently don't QAQC the time variable. @kerfoot what are your thoughts on this?

**Comment by kerfoot** [comment] 2022-09-08 19:44
Data provider responsibility. Closing

**Closed by kerfoot** 2022-09-08 19:44 UTC
